version: "3"
services:
  api:
    build:
      context: .
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    container_name: express
    networks:
      - api-network
networks:
  api-network:
    driver: bridge